# docker-compose.yml file
version: "3.5"

services:
  mongo_one:
    container_name: mongo1
    image: "mongo:4.0-xenial" #should specify version mongo here
    command: --replSet my-mongo-set
    networks:
      - localnet
    ports:
      - "27018:27017"
    restart: always

  mongo_two:
    container_name: mongo2
    image: "mongo:4.0-xenial" #should specify version mongo here
    command: --replSet my-mongo-set
    networks:
      - localnet
    ports:
      - "27019:27017"
    restart: always

  mongo_three:
    container_name: mongo3
    image: "mongo:4.0-xenial" #should specify version mongo here
    command: --replSet my-mongo-set
    networks:
      - localnet
    ports:
      - "27020:27017"
    restart: always

networks:
  localnet:
    attachable: true